// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDWd24s0AeS3R1-zR1-fJlVVX-5Dzcaw',
    appId: '1:772853641519:web:5baec9a5dca8a8879db1da',
    messagingSenderId: '772853641519',
    projectId: 'movie-gratis-fc0ad',
    authDomain: 'movie-gratis-fc0ad.firebaseapp.com',
    storageBucket: 'movie-gratis-fc0ad.firebasestorage.app',
    measurementId: 'G-8FY1VNNFC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNSXUSqxyJzIf-TR-Ca4HhVlxLxncSNh0',
    appId: '1:772853641519:android:5497cdb647e260de9db1da',
    messagingSenderId: '772853641519',
    projectId: 'movie-gratis-fc0ad',
    storageBucket: 'movie-gratis-fc0ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxduKGCbUHuJbP0fD2ySftdAbMyBHehTg',
    appId: '1:772853641519:ios:24f9361abf12edb39db1da',
    messagingSenderId: '772853641519',
    projectId: 'movie-gratis-fc0ad',
    storageBucket: 'movie-gratis-fc0ad.firebasestorage.app',
    iosBundleId: 'com.example.movielix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxduKGCbUHuJbP0fD2ySftdAbMyBHehTg',
    appId: '1:772853641519:ios:24f9361abf12edb39db1da',
    messagingSenderId: '772853641519',
    projectId: 'movie-gratis-fc0ad',
    storageBucket: 'movie-gratis-fc0ad.firebasestorage.app',
    iosBundleId: 'com.example.movielix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfDWd24s0AeS3R1-zR1-fJlVVX-5Dzcaw',
    appId: '1:772853641519:web:478b38d075ada97a9db1da',
    messagingSenderId: '772853641519',
    projectId: 'movie-gratis-fc0ad',
    authDomain: 'movie-gratis-fc0ad.firebaseapp.com',
    storageBucket: 'movie-gratis-fc0ad.firebasestorage.app',
    measurementId: 'G-B44VF9NEV5',
  );
}
